// Generated by ts-to-zod
import { z } from 'zod';

export const customerSchema = z.object({
	id: z.number(),
	name: z.string(),
	phone_number: z.null(),
	email: z.string(),
	created_at: z.date(),
});

export const cardSchema = z.object({
	first_6digits: z.string(),
	last_4digits: z.string(),
	issuer: z.string(),
	country: z.string(),
	type: z.string(),
	expiry: z.string(),
});

export const dataSchema = z.object({
	id: z.number(),
	tx_ref: z.string(),
	flw_ref: z.string(),
	device_fingerprint: z.string().optional(),
	amount: z.number(),
	currency: z.string().optional(),
	charged_amount: z.number().optional(),
	app_fee: z.number().optional(),
	merchant_fee: z.number().optional(),
	processor_response: z.string().optional(),
	auth_model: z.string().optional(),
	ip: z.string().optional(),
	narration: z.string().optional(),
	status: z.string(),
	payment_type: z.string().optional(),
	created_at: z.date().optional(),
	account_id: z.number().optional(),
	customer: customerSchema.optional(),
	card: cardSchema.optional(),
});

export const FlwWebHookPayloadSchema = z.object({
	event: z.string(),
	data: dataSchema,
});

export const flwHeaderValidation = z.object({
	'verif-hash': z.string({ required_error: 'required header is a string' }),
});
